### ISSUE TITLE
reversed genesis hash at lib/Block.js

### ISSUE THREAD

**Issue by cryptozeny** [BitzenyCoreDevelopers/bitcore-bitzeny#1]
`bitcore-bitzeny/lib/Block.js` file

```js
hash: hex('CEF5B89F4EBF38A73CD440439EDACA4AFA7C7AD82BE281473B9E5EE5F7090000'),
```

The original genesis hash was hard coded at `bitzeny/src/chainparams.cpp`:
```cpp
assert(consensus.hashGenesisBlock == uint256S("0x000009f7e55e9e3b4781e22bd87a7cfa4acada9e4340d43ca738bf4e9fb8f5ce"));
```

Original
```ssh
CEF5B89F4EBF38A73CD440439EDACA4AFA7C7AD82BE281473B9E5EE5F7090000
```

Reversed
```js
000009F7E55E9E3B4781E22BD87A7CFA4ACADA9E4340D43CA738BF4E9FB8F5CE
```

I would to know about it. Why this genesis hash is reversed? The merkle root is also reversed...

ジェネシスハッシュがbitcoreで反対へと覆されています。 これの理由を知ってる方がありますか?

**Comment by zenywallet** [comment]
It depends on the difference in hex handling between javascript and c library. There is a possibility that I make a mistake. . .

**Comment by cryptozeny** [comment]
i don't think so you have a mistake. this code works correctly i think...

**Comment by zenywallet** [comment]
It is the difference between big endian and little endian.
It seems code is correct.
